"""empty message

Revision ID: ccc793fecff4
Revises: f44cc787ebf5
Create Date: 2021-10-08 16:05:44.146867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc793fecff4'
down_revision = 'f44cc787ebf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounter', 'Name')
    op.drop_column('encounter', 'Duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounter', sa.Column('Duration', sa.VARCHAR(length=120), nullable=True))
    op.add_column('encounter', sa.Column('Name', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
