"""empty message

Revision ID: f44cc787ebf5
Revises: 
Create Date: 2021-10-08 15:38:00.572373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44cc787ebf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EncId', sa.String(length=64), nullable=True),
    sa.Column('Name', sa.String(length=120), nullable=True),
    sa.Column('Duration', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_EncId'), 'encounter', ['EncId'], unique=True)
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EncId', sa.String(length=64), nullable=True),
    sa.Column('Ally', sa.String(length=64), nullable=True),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('StartTime', sa.DateTime(), nullable=True),
    sa.Column('EndTime', sa.DateTime(), nullable=True),
    sa.Column('Duration', sa.String(length=64), nullable=True),
    sa.Column('Damage', sa.Integer(), nullable=True),
    sa.Column('DamagePerc', sa.Float(), nullable=True),
    sa.Column('Kills', sa.Integer(), nullable=True),
    sa.Column('Healed', sa.Integer(), nullable=True),
    sa.Column('HealedPerc', sa.Float(), nullable=True),
    sa.Column('CritHeals', sa.Integer(), nullable=True),
    sa.Column('Heals', sa.Integer(), nullable=True),
    sa.Column('CureDispels', sa.Integer(), nullable=True),
    sa.Column('PowerDrain', sa.Integer(), nullable=True),
    sa.Column('PowerReplenish', sa.Integer(), nullable=True),
    sa.Column('DPS', sa.Float(), nullable=True),
    sa.Column('EncDPS', sa.Float(), nullable=True),
    sa.Column('EncHPS', sa.Float(), nullable=True),
    sa.Column('Hits', sa.Integer(), nullable=True),
    sa.Column('CritHits', sa.Integer(), nullable=True),
    sa.Column('Blocked', sa.Integer(), nullable=True),
    sa.Column('Misses', sa.Integer(), nullable=True),
    sa.Column('Swings', sa.Integer(), nullable=True),
    sa.Column('HealsTaken', sa.Integer(), nullable=True),
    sa.Column('DamageTaken', sa.Integer(), nullable=True),
    sa.Column('Deaths', sa.Integer(), nullable=True),
    sa.Column('ToHit', sa.Float(), nullable=True),
    sa.Column('CritDamPerc', sa.Float(), nullable=True),
    sa.Column('CritHealPerc', sa.Float(), nullable=True),
    sa.Column('CritTypes', sa.String(length=64), nullable=True),
    sa.Column('ThreatStr', sa.String(length=64), nullable=True),
    sa.Column('ThreatDelta', sa.Integer(), nullable=True),
    sa.Column('Job', sa.String(length=64), nullable=True),
    sa.Column('ParryPct', sa.Float(), nullable=True),
    sa.Column('BlockPct', sa.Float(), nullable=True),
    sa.Column('IncToHit', sa.Float(), nullable=True),
    sa.Column('OverHealPct', sa.Float(), nullable=True),
    sa.Column('DirectHitPct', sa.Float(), nullable=True),
    sa.Column('DirectHitCount', sa.Integer(), nullable=True),
    sa.Column('CritDirectHitCount', sa.Integer(), nullable=True),
    sa.Column('CritDirectHitPct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entry')
    op.drop_index(op.f('ix_encounter_EncId'), table_name='encounter')
    op.drop_table('encounter')
    # ### end Alembic commands ###
