from app import db

class LogEntry(db.Model):
    """"""

    id = db.Column(db.Integer, primary_key=True)
    encId = db.Column(db.String(64))
    ally = db.Column(db.String(64))
    nom = db.Column(db.String(64))
    startTime = db.Column(db.DateTime())
    endTime = db.Column(db.DateTime())
    duration = db.Column(db.String(64))
    damage = db.Column(db.Integer)
    damagePerc = db.Column(db.Integer)
    kills = db.Column(db.Integer)
    healed = db.Column(db.Integer)
    healedPerc = db.Column(db.Integer)
    critHeals = db.Column(db.Integer)
    heals = db.Column(db.Integer)
    cureDisplels = db.Column(db.Integer)
    powerDrain = db.Column(db.Integer)
    powerReplanish = db.Column(db.Integer)
    dps = db.Column(db.Float())
    encDps = db.Column(db.Float())
    encHps = db.Column(db.Float())
    hits = db.Column(db.Integer)
    critHits = db.Column(db.Integer)
    blocked = db.Column(db.Integer)
    misses = db.Column(db.Integer)
    swings = db.Column(db.Integer)
    healTaken = db.Column(db.Integer)
    damageTaken = db.Column(db.Integer)
    death = db.Column(db.Integer)
    toHit = db.Column(db.Float())
    critDamagePerc = db.Column(db.Integer)
    critHealPerc = db.Column(db.Integer)
    critTypes = db.Column(db.String(64))
    threatStr = db.Column(db.String(64))
    threatDelta = db.Column(db.Integer)
    job = db.Column(db.String(64))
    ParryPct = db.Column(db.Integer)
    BlockPct = db.Column(db.Integer)
    BlockPct = db.Column(db.Integer)
    IncToHit = db.Column(db.Float())
    DirectHitPct = db.Column(db.Integer)
    DirectHitCount = db.Column(db.Integer)
    CritDirectHitCount = db.Column(db.Integer)
    CritDirectHitPct = db.Column(db.Integer)
    
    def __repr__(self):
        return f"LogEntry {self.id}"