from app import db

class LogEntry(db.Model):
    """"""

    id = db.Column(db.Integer, primary_key=True)
    EncId = db.Column(db.String(64))
    Ally = db.Column(db.String(64))
    Name = db.Column(db.String(64))
    StartTime = db.Column(db.DateTime())
    EndTime = db.Column(db.DateTime())
    Duration = db.Column(db.String(64))
    Damage = db.Column(db.Integer)
    DamagePerc = db.Column(db.Float())
    Kills = db.Column(db.Integer)
    Healed = db.Column(db.Integer)
    HealedPerc = db.Column(db.Float())
    CritHeals = db.Column(db.Integer)
    Heals = db.Column(db.Integer)
    CureDispels = db.Column(db.Integer)
    PowerDrain = db.Column(db.Integer)
    PowerReplenish = db.Column(db.Integer)
    DPS = db.Column(db.Float())
    EncDPS = db.Column(db.Float())
    EncHPS = db.Column(db.Float())
    Hits = db.Column(db.Integer)
    CritHits = db.Column(db.Integer)
    Blocked = db.Column(db.Integer)
    Misses = db.Column(db.Integer)
    Swings = db.Column(db.Integer)
    HealsTaken = db.Column(db.Integer)
    DamageTaken = db.Column(db.Integer)
    Deaths = db.Column(db.Integer)
    ToHit = db.Column(db.Float())
    CritDamPerc = db.Column(db.Float())
    CritHealPerc = db.Column(db.Float())
    CritTypes = db.Column(db.String(64))
    ThreatStr = db.Column(db.String(64))
    ThreatDelta = db.Column(db.Integer)
    Job = db.Column(db.String(64))
    ParryPct = db.Column(db.Float())
    BlockPct = db.Column(db.Float())
    IncToHit = db.Column(db.Float())
    OverHealPct = db.Column(db.Float())
    DirectHitPct = db.Column(db.Float())
    DirectHitCount = db.Column(db.Integer)
    CritDirectHitCount = db.Column(db.Integer)
    CritDirectHitPct = db.Column(db.Float())
    
    def __repr__(self):
        return f"LogEntry {self.id}"